linters:
  disable-all: true

  enable:
    - decorder
    - dupl
    - errname
    - errorlint
    - funlen
    - goconst
    - godot
    - gofmt
    - gomnd
    - goprintffuncname
    - gosec
    - gocritic
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - makezero
    - nestif
    - nilerr
    - nilnil
    - predeclared
    - testpackage
    - unconvert
