services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./fixtures.sql:/docker-entrypoint-initdb.d/02_fixtures.sql
    ports:
      - 127.0.0.1:5432:5432

volumes:
  pg_data:


networks:
  karten:
