version: "3"

services:
  karten:
    image: yuko42/karten:master
    networks:
      - karten
      - traefik_area
    depends_on:
      - karten-backend
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_area
        - traefik.http.services.karten-service.loadbalancer.server.port=80

        - traefik.http.routers.karten.tls=true
        - traefik.http.routers.karten.rule=Host(`karten.rm-yuko.cloud`)
        - traefik.http.routers.karten.entrypoints=websecure

        - traefik.http.routers.insecure-karten.rule=Host(`karten.rm-yuko.cloud`)
        - traefik.http.routers.insecure-karten.entrypoints=web
        - traefik.http.routers.insecure-karten.middlewares=force-https@file

  karten-backend:
    image: yuko42/karten-backend:master
    env_file: .env.pie
    volumes:
      - karten_media:/root/media
      - sessions_store:/root/sessions
    networks:
      - karten
      - traefik_area
    depends_on:
      - database
      - migrator
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_area
        - traefik.http.services.karten-api-service.loadbalancer.server.port=4000

        - traefik.http.routers.karten-api.tls=true
        - traefik.http.routers.karten-api.rule=Host(`api.karten.rm-yuko.cloud`)
        - traefik.http.routers.karten-api.entrypoints=websecure

        - traefik.http.routers.insecure-karten-api.rule=Host(`api.karten.rm-yuko.cloud`)
        - traefik.http.routers.insecure-karten-api.entrypoints=web
        - traefik.http.routers.insecure-karten-api.middlewares=force-https@file

  migrator:
    image: yuko42/karten-backend-migrator:master
    networks:
      - karten
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    env_file: .env.pie
    command: ["db", "migrate"]

  database:
    image: postgres:latest
    networks:
      - karten
    env_file: .env.pie
    volumes:
      - pg_data:/var/lib/postgresql/data

  static-server:
    image: nginx:1.25-alpine
    networks:
      - karten
      - traefik_area
    volumes:
      - karten_media:/usr/share/nginx/html:ro
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_area
        - traefik.http.services.karten-media-service.loadbalancer.server.port=80

        - traefik.http.routers.karten-media.tls=true
        - traefik.http.routers.karten-media.rule=Host(`media.karten.rm-yuko.cloud`)
        - traefik.http.routers.karten-media.entrypoints=websecure

        - traefik.http.routers.insecure-karten-media.rule=Host(`media.karten.rm-yuko.cloud`)
        - traefik.http.routers.insecure-karten-media.entrypoints=web
        - traefik.http.routers.insecure-karten-media.middlewares=force-https@file

volumes:
  pg_data:
  sessions_store:
  karten_media:


networks:
  karten:

  traefik_area:
    external: true
