services:
  karten:
    image: cosmtrek/air:v1.42.0
    environment:
      DEBUG: "1"
      API_HOST: "0.0.0.0:4000"
      STORE_DSN: "postgres://karten:karten@db:5432/karten?sslmode=disable&search_path=karten"
      FILE_STORAGE_PATH: "/app/media"

      ALLOW_ORIGINS: ${ALLOW_ORIGINS:-http://127.0.0.1:3000}
      MEDIA_URL: ${MEDIA_URL:-http://127.0.0.1:4001}
      COOKIE_DOMAIN: $COOKIE_DOMAIN
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 127.0.0.1:4000:4000

  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: karten
      POSTGRES_PASSWORD: karten
      POSTGRES_DB: karten
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./fixtures.sql:/docker-entrypoint-initdb.d/02_fixtures.sql
    ports:
      - 127.0.0.1:5432:5432

  static-server:
    image: nginx:1.21-alpine
    volumes:
      - ./media:/usr/share/nginx/html/
    ports:
      - 127.0.0.1:4001:80

volumes:
  pg_data:


networks:
  karten:
