services:
  karten:
    image: cosmtrek/air:v1.42.0
    environment:
      DEBUG: true
      API_HOST: "0.0.0.0:4000"
      STORE_DSN: "postgres://karten:karten@db:5432/karten?sslmode=disable&search_path=karten"
      FILE_STORAGE_PATH: "/app/media"
      SESSIONS_STORE_PATH: "/tmp"

      ALLOW_ORIGINS: ${ALLOW_ORIGINS:-http://127.0.0.1:3000}
      MEDIA_URL: ${MEDIA_URL:-http://127.0.0.1:4001}
      COOKIE_DOMAIN: $COOKIE_DOMAIN
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 127.0.0.1:4000:4000
    depends_on:
      - db

  migrator:
    build:
      context: '.'
      target: migrator
    depends_on:
      - db
    environment:
      STORE_DSN: "postgres://karten:karten@db:5432/karten?sslmode=disable&search_path=karten"
    command: [ "db", "migrate" ]

  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: karten
      POSTGRES_PASSWORD: karten
      POSTGRES_DB: karten
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  static-server:
    image: nginx:1.21-alpine
    volumes:
      - ./media:/usr/share/nginx/html/
    ports:
      - 127.0.0.1:4001:80

volumes:
  pg_data:


networks:
  karten:
