services:
  karten-intergation-tests:
    image: golang:1.21
    command: bash -c "make migrate && make test-integration"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      INTEGRATION_TESTS: true
      STORE_DSN: postgres://tester:tester@karten-test-db:5432/test?sslmode=disable
    networks:
      - karten-test
    depends_on:
      - karten-test-db

  karten-test-db:
    image: postgres:16
    logging:
      driver: "none"
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: tester
      POSTGRES_DB: test
    networks:
      - karten-test

networks:
  karten-test:
